version: "3.9"

services:
  web:
    build: .
    ports:
      - "4000:4000" 
    depends_on:
      - db
    env_file: timemanager_envi.env
    restart: always
    #networks: 
      #- mynw
  db:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
    
    restart: always 
    #networks: 
      #- mynw