version: '3.9'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    stdin_open: true
    tty: true

  db:
    image: postgres:15.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=timemanager_dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5500:5432"
    restart: always
